services:
  app:
    image: composer:latest
    working_dir: /app
    entrypoint: ["php"]
    volumes:
      - ./:/app
    command: ["bin/sync_guapo_data.php"]

  composer:
    image: composer:latest
    working_dir: /app
    volumes:
      - ./:/app

  tests:
    image: composer:latest
    working_dir: /app
    entrypoint: ["php"]
    volumes:
      - ./:/app
    command: ["vendor/bin/phpunit"]